using System;

namespace Assets.Scripts.Games.PuntosCardinalesActivity {
	public enum Possibilities {
		BEHIND, BEHIND_STREET, LEFT, LEFT_STREET, RIGHT, RIGHT_STREET, BETWEEN_VERTICAL, BETWEEN_HORIZONTAL, IN_FRONT, IN_FRONT_STREET,
		LEFT_SCHOOL_STREET, RIGHT_SCHOOL_STREET, IN_FRONT_SCHOOL_STREET, EMPTY
	}
}